INSERT INTO palabras (id, palabra, porcentage, sinonimo) VALUES
(1, 'Diagnóstico', 90, 'Evaluación clínica'),
(2, 'Síntoma', 85, 'Manifestación clínica'),
(3, 'Enfermedad', 95, 'Patología'),
(4, 'Tratamiento', 90, 'Terapia'),
(5, 'Cirugía', 100, 'Intervención quirúrgica'),
(6, 'Paciente', 70, 'Enfermo'),
(7, 'Fiebre', 100, 'Pirexia'),
(8, 'Dolor', 80, 'Algias'),
(9, 'Análisis', 85, 'Estudio clínico'),
(10, 'Vacuna', 80, 'Inmunización'),
(11, 'Infección', 75, 'Contagio'),
(12, 'Herida', 90, 'Lesión'),
(13, 'Medicamento', 95, 'Fármaco'),
(14, 'Presión arterial', 100, 'Tensión arterial'),
(15, 'Radiografía', 95, 'Rayos X'),
(16, 'Cáncer', 100, 'Neoplasia maligna'),
(17, 'Deshidratación', 70, 'Hipovolemia'),
(18, 'Alergia', 85, 'Hipersensibilidad'),
(19, 'Parto', 95, 'Alumbramiento'),
(20, 'Órgano', 75, 'Víscera');
